image: node:16

stages:
  - install
  - build
  - deploy

install_dependencies:
  stage: install
  script:
    - npm install

build_project:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist

deploy_to_production:
  stage: deploy
  script:
    - echo "Deploying to production server"  - # Add your deployment commands here (e.g., SSH into server, copy files)
    
  only:
    - main  # Change this to your main branch name
